apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-hello-world
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: flask-hello-world=docker.io/mateussebastiao/flask_hello-world
    argocd-image-updater.argoproj.io/flask-hello-world.update-strategy: semver
    argocd-image-updater.argoproj.io/flask-hello-world.version: ">=1.0.0"
    argocd-image-updater.argoproj.io/flask-hello-world.allow-tags: regexp:^[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/flask-hello-world.write-back-method: git
    argocd-image-updater.argoproj.io/flask-hello-world.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/flask-hello-world.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:argocd-image-updater/helm-manifests/values.yaml,git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/Mateus-Sebastiao/gitops-argocd.git
    targetRevision: main
    path: argocd-image-updater/helm-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true