replicaCount: 1

image:
  repository: docker.io/mateussebastiao/flask_hello-world
  tag: "v1.0.0"
  pullPolicy: IfNotPresent
  containerPort: 8080

service:
  type: ClusterIP
  port: 80

securityContext: {}
