apiVersion: v1 
kind: Service
metadata: 
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec: 
  type: {{ .Values.service.type }}
  ports: 
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.containerPort }}
      protocol: TCP
  selector: 
    app.kubernetes.io/name: {{ .Chart.Name }}