name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'argocd-image-updater/app/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask_hello-world:${{ github.sha }} ./argocd-image-updater/app
          docker tag ${{ secrets.DOCKER_USERNAME }}/flask_hello-world:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/flask_hello-world:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/flask_hello-world:${{ github.sha }}
#          docker push ${{ secrets.DOCKER_USERNAME }}/flask_hello-world:latest
