name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'argocd-image-updater/app/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          VERSION="1.0.${{ github.run_number }}"
          IMAGE=${{ secrets.DOCKER_USERNAME }}/flask_hello-world
          docker build -t $IMAGE:$VERSION ./argocd-image-updater/app
          docker tag $IMAGE:$VERSION $IMAGE:latest

      - name: Push Docker image
        run: |
          VERSION="1.0.${{ github.run_number }}"
          IMAGE=${{ secrets.DOCKER_USERNAME }}/flask_hello-world
          docker push $IMAGE:$VERSION
          docker push $IMAGE:latest

